name: 'PR Genie 🧞'
description: 'AI-powered code review assistant for GitHub pull requests that provides intelligent code analysis, suggestions, and best practices recommendations.'

author: 'david-wagih'

inputs:
  openai-key:
    description: 'OpenAI API key for code review'
    required: true
    sensitive: true

outputs:
  total_files:
    description: 'Total number of files reviewed'
  additions:
    description: 'Total number of lines added'
  deletions:
    description: 'Total number of lines deleted'
  total_changes:
    description: 'Total number of lines changed'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'magic'
  color: 'purple'

permissions:
  contents: read
  pull-requests: write

# Security best practices
security:
  # Ensure the action only runs on pull request events
  events:
    - pull_request
  # Minimize token permissions
  token:
    permissions:
      contents: read
      pull-requests: write
  # Prevent workflow from running on forks
  prevent-fork: true 