name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create Release PR
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          package-name: pr-genie
          token: ${{ secrets.RELEASE_TOKEN }}
          default-branch: master
          versioning-strategy: default
          pull-request-title-pattern: "chore: release ${version}"
          bootstrap-sha: dbf5d0fc658dc51b618bb759acd82625596f08a4
          include-v-in-tag: true
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"refactor","section":"Refactoring","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"test","section":"Tests","hidden":true},
              {"type":"deps","section":"Dependencies","hidden":false}
            ]
          
      - name: Create GitHub Release
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          name: Release ${{ steps.release.outputs.tag_name }}
          body: ${{ steps.release.outputs.body }}
          draft: false
          prerelease: false 