name: Test PR Genie

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install @actions/core @actions/github @octokit/rest
          
      - name: Build
        run: npm run build
      
      - name: Run PR Genie
        id: pr-genie
        uses: ./ # Uses the action in the root directory
        with:
          github-token: ${{ github.token }}
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          pr-number: ${{ github.event.pull_request.number }}
          config-file: pr-genie.config.json  # Optional config file

      # Add a test step to verify the action outputs
      - name: Verify Action Outputs
        run: |
          echo "Total files: ${{ steps.pr-genie.outputs.total_files }}"
          echo "Additions: ${{ steps.pr-genie.outputs.additions }}"
          echo "Deletions: ${{ steps.pr-genie.outputs.deletions }}"
          echo "Total changes: ${{ steps.pr-genie.outputs.total_changes }}" 